
services:
  jobrunr-testbed-worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JOBRUNR_DB_URL: 
      JOBRUNR_DB_USER: root
      JOBRUNR_DB_PASS: password
    restart: unless-stopped


